# 应用服务 WEB 访问端口
server:
  port: 8080

# 滑动验证，底图路径，不配置将使用默认图片
# 支持全路径
# 支持项目路径,以classpath:开头,取resource目录下路径,例：classpath:images/jigsaw
aj:
  captcha:
    jigsaw: classpath:images/jigsaw
#滑动验证，底图路径，不配置将使用默认图片
##支持全路径
# 支持项目路径,以classpath:开头,取resource目录下路径,例：classpath:images/pic-click
    pic-click: classpath:images/pic-click
    cacheType: redis
    # local缓存的阈值,达到这个值，清除缓存
    # aj.captcha.cache-number=1000
    cacheNumber: 1000
    # local定时清除过期缓存(单位秒),设置为0代表不执行
    timingClear: 180
    # 验证码类型default两种都实例化。
    type: default
    # 校验滑动拼图允许误差偏移量(默认5像素)
    slipOffset: 5
    # 滑动干扰项(0/1/2)
    interferenceOptions: 2
    #点选字体样式 默认Font.BOLD
    fontStyle: 1
    #点选字体字体大小
    fontSize: 25
    historyDataClearEnable: false
    # 接口请求次数一分钟限制是否开启 true|false
    reqFrequencyLimitEnable: false
    # 验证失败5次，get接口锁定
    reqgetlocklimit: 5
    # 验证失败后，锁定时间间隔,s
    reqgetlockseconds: 360
    # get接口一分钟内请求数限制
    reqgetminutelimit: 30
    # check接口一分钟内请求数限制
    reqcheckminutelimit: 60
    # verify接口一分钟内请求数限制
    reqverifyminutelimit: 60
    waterMark: water-mark
    aesStatus: true

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: